### ISSUE TITLE
SMURF should not have to be loaded in production mode

### ISSUE THREAD

**Issue by paulkoegel** [railslove/smurfville#2]
I only use smurf to inspect my styles in development mode or on staging. i can't see any reason why i'd need it on production.

the way it's coded at the moment, however, i have to load it in all environments (smurf is included in the routes) and it's in the Gemfile's global scope.
what i'd love to have is to be able to move it to the :development or :development, :staging groups like this:

group :development, :staging do
  gem 'smurf-rails', :git => 'https://github.com/railslove/smurf',
:require => 'smurf'
end

**Comment by jhilden** [comment]
I updated the suggested initializer and routes.rb file in the README, so they won't do anything if Smurfville module is not defined.  Is that enough?

**Comment by paulkoegel** [comment]
looks good. closing this now.
not sure though you need the "!= nil"s
when running irb i get these:

> defined? x
>  => nil 
> defined? nil
>  => "nil" 
> defined? false
>  => "false" 
> defined? Smurfville
>  => nil 

all return values except for the undeclared x and Smurfville are truthy

interestingly:

> defined? (54/0)
>  => "method"
