### ISSUE TITLE
we should consider changing SMURF's name

### ISSUE THREAD

**Issue by paulkoegel** [railslove/smurfville#3]
there is already a smurf gem: http://rubygems.org/gems/smurf

the current workaround of appending -rails to the gem's name conflicts with bundler's conventions (cf. http://guides.rubygems.org/patterns). even if we changed it to _rails people might still think it's the other smurf gem's rails-specific version (like compass-rails).

i'd suggest the names
SMURF on SMACSS
or
SMACSSy SMURF

both indicate clearly how much we're indebted to SMACSS and offer a great possibilities for logos:
http://imgur.com/QK9yH

**Comment by jhilden** [comment]
The name of the gem is now "smurfville" - Home of SMURF

**Comment by paulkoegel** [comment]
cool. i'm sure we'll find a way to fit smurfville on a pack of kellogg's smacks :)
btw: http://en.wikipedia.org/wiki/The_Smurfs#Smurf_village
